version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: rssagg
      POSTGRES_USER: rssadmin
      POSTGRES_PASSWORD: rss@1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
